#if !defined(AFX_PCQNG_H__6F7D604E_235C_4343_898E_697A4763DE6B__INCLUDED_)
#define AFX_PCQNG_H__6F7D604E_235C_4343_898E_697A4763DE6B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPCQNG wrapper class

class CPCQNG : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPCQNG)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x59da5e62, 0x69a4, 0x4505, { 0xa9, 0xd0, 0xca, 0xee, 0x53, 0xc4, 0x9e, 0x7 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void Open();
	void Close();
	float GetMode();
	void SetMode(float Mode);
	void Clear();
	void Reset();
	long GetRandInt32();
	double GetRandUniform();
	double GetRandNormal();
	VARIANT GetRandBytes(long Length);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PCQNG_H__6F7D604E_235C_4343_898E_697A4763DE6B__INCLUDED_)
